apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config
  labels:
    app: todo-app
data:
  APP_NAME: "To-Do List Manager"
  APP_VERSION: "1.0.0"
  DEBUG: "false"
  HOST: "0.0.0.0"
  PORT: "8000"
  # Üretim ortamında buraya PostgreSQL adresi girilmelidir
  DATABASE_URL: "sqlite:///./todo.db"
